# Project 3: Classification__

### __Objective__
In this lab, you will apply supervised learning (classification) models to predict one of the following
1. **Loan Approval Outcomes** : The dataset includes demographic, financial, and credit history features of loan applicants.
2. **Airline Passenger Satisfaction** : Customer satisfaction scores from 120,000+ airline passengers, including additional information about each passenger, their flight, and type of travel, as well as ther evaluation of different factors like cleanliness, comfort, service, and overall experience.
3. **Hotel Booking Cancellations** : booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things

### __Requirements__
Your task is to explore the data, clean and preprocess it appropriately, and build predictive models. Specifically, you must:
1. **Perform EDA**: Explore distributions, identify missing values, and check for class imbalance in the target variable.
2. **Preprocess the Data**: Handle categorical encodings, impute missing values, and scale your features. *Hint: Make sure to perform your train-test split BEFORE scaling to prevent data leakage!*
3. **Train Classification Models**: train **two** classification models (**Logistic Regression** and **KNN**).
5. **Evaluate & Compare**: Evaluate models using accuracy, precision, recall, F1-score, and confusion matrices. 

### __Deliverables__
You are expected to document your workflow using Markdown cells. Do not just write code; explain your **rationale**. Include insights from your EDA, justify your preprocessing decisions, and conclude with a comparative analysis discussing which of the three models performed best and why.

---

## __Data Dictionary__

___Copy you assigned dataset's dictionary from the guidleines___

---

## Setup and Data Loading
Import your libraries and load the dataset.

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Add your sklearn imports here...

In [6]:
# Load the dataset
# df = pd.read_csv('...')
# df.head()
df = pd.read_csv('data/loan_data.csv')

In [7]:
df

,Unnamed: 0,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,0,22.0,female,MASTER,$71948.0,0,RENT,35000.0$,personal,16.02,0.49,3.0,561,No,1
1,1,21.0,female,High School,12282.0$,0,OWN,$1000.0,EDUCATION,11.14,0.08,2.0,504,yes,0
2,2,25.0,female,High School,12438.0$,3,MORTGAGE,$5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,3,23.0,female,Bachelor,$79753.0,0,RENT,$35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,4,24.0,MALE,Master,66135.0$,1,RENT,$35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47245,47245,23.0,MALE,Associate,51496.0$,2,MORTGAGE,$2000.0,EDUCATION,15.20,0.04,2.0,682,No,1
47246,47246,28.0,male,Bachelor,202887.0$,5,RENT,$14611.0,HOMEIMPROVEMENT,15.96,0.07,8.0,671,No,1
47247,47247,37.0,female,High School,300843.0$,15,mortgage,$34000.0,EDUCATION,14.79,0.11,16.0,658,yes,0
47248,47248,35.0,MALE,Master,72970.0$,15,OWN,$24000.0,PERSONAL,12.53,0.33,9.0,656,No,0
47249,47249,21.0,male,Associate,$28319.0,0,OTHER,$2400.0,EDUCATION,12.21,0.08,4.0,628,yes,0

In [9]:
df.describe()

,Unnamed: 0,person_age,person_emp_exp,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
count,47250.000000,47250.000000,47250.000000,47250.000000,47250.000000,47250.000000,47250.000000,47250.000000
mean,23624.500000,27.752550,5.398921,11.010191,0.139940,5.862222,632.586709,0.221947
std,13640.044446,6.032801,6.051270,2.981758,0.087238,3.873836,50.462422,0.415560
min,0.000000,20.000000,0.000000,5.420000,0.000000,2.000000,390.000000,0.000000
25%,11812.250000,24.000000,1.000000,8.590000,0.070000,3.000000,601.000000,0.000000
50%,23624.500000,26.000000,4.000000,11.010000,0.120000,4.000000,640.000000,0.000000
75%,35436.750000,30.000000,8.000000,13.020000,0.190000,8.000000,670.000000,0.000000
max,47249.000000,144.000000,125.000000,20.000000,0.660000,30.000000,850.000000,1.000000

In [11]:
df.describe(include='all')

,Unnamed: 0,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
count,47250.000000,47250.000000,47250,47250,47250,47250.000000,47250,47250,47250,47250.000000,47250.000000,47250.000000,47250.000000,47250,47250.000000
unique,NaN,NaN,3,8,39432,NaN,6,5327,9,NaN,NaN,NaN,NaN,4,NaN
top,NaN,NaN,female,Associate,8000.0$,NaN,RENT,$10000.0,MEDICAL,NaN,NaN,NaN,NaN,Yes,NaN
freq,NaN,NaN,21174,12612,8,NaN,24593,1931,8981,NaN,NaN,NaN,NaN,16770,NaN
mean,23624.500000,27.752550,NaN,NaN,NaN,5.398921,NaN,NaN,NaN,11.010191,0.139940,5.862222,632.586709,NaN,0.221947
std,13640.044446,6.032801,NaN,NaN,NaN,6.051270,NaN,NaN,NaN,2.981758,0.087238,3.873836,50.462422,NaN,0.415560
min,0.000000,20.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,5.420000,0.000000,2.000000,390.000000,NaN,0.000000
25%,11812.250000,24.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,8.590000,0.070000,3.000000,601.000000,NaN,0.000000
50%,23624.500000,26.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,11.010000,0.120000,4.000000,640.000000,NaN,0.000000
75%,35436.750000,30.000000,NaN,NaN,NaN,8.000000,NaN,NaN,NaN,13.020000,0.190000,8.000000,670.000000,NaN,0.000000
max,47249.000000,144.000000,NaN,NaN,NaN,125.000000,NaN,NaN,NaN,20.000000,0.660000,30.000000,850.000000,NaN,1.000000

In [15]:
df.sort_values('person_age')

,Unnamed: 0,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
16339,16339,20.0,MALE,Bachelor,226515.0$,0,mortgage,$2000.0,personal,8.59,0.01,2.0,598,Yes,0
1313,1313,20.0,male,Bachelor,78039.0$,0,RENT,$16000.0,VENTURE,15.31,0.21,4.0,671,No,1
15830,15830,20.0,MALE,Associate,$226622.0,0,MORTGAGE,$2000.0,EDUCATION,8.59,0.01,4.0,687,Yes,0
15417,15417,20.0,female,High School,$162939.0,0,mortgage,$15000.0,VENTURE,15.96,0.09,2.0,640,Yes,0
17196,17196,20.0,male,Associate,78989.0$,0,MORTGAGE,$4800.0,VENTURE,9.99,0.06,4.0,678,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,575,123.0,female,High School,97140.0$,101,RENT,20400.0$,EDUCATION,10.25,0.21,3.0,805,Yes,0
747,747,123.0,MALE,Bachelor,94723.0$,100,RENT,$20000.0,VENTURE,11.01,0.21,4.0,714,Yes,0
183,183,144.0,male,Associate,$241424.0,121,MORTGAGE,$6000.0,EDUCATION,11.86,0.02,2.0,807,No,0
32297,32297,144.0,female,Associate,$7200766.0,124,MORTGAGE,5000.0$,PERSONAL,12.73,0.00,25.0,850,No,0
81,81,144.0,MALE,Bachelor,300616.0$,125,RENT,$4800.0,VENTURE,13.57,0.02,3.0,789,No,0

In [21]:
df['previous_loan_defaults_on_file'].unique()

<StringArray>
[' No ', 'yes', 'No', 'Yes']
Length: 4, dtype: str

In [23]:
df['person_gender'].unique()

<StringArray>
['female', 'MALE', 'male']
Length: 3, dtype: str

In [24]:
df['person_education'].unique()

<StringArray>
[       'MASTER',   'High School', ' High School ',      'Bachelor',
        'Master',    ' Bachelor ',     'Associate',     'Doctorate']
Length: 8, dtype: str

In [25]:
df['person_home_ownership'].unique()

<StringArray>
['RENT', 'OWN', 'MORTGAGE', 'mortgage', 'OTHER', 'own']
Length: 6, dtype: str

In [26]:
df['loan_intent'].unique()

<StringArray>
[           'personal',           'EDUCATION',             'MEDICAL',
             'VENTURE',         ' EDUCATION ',            'PERSONAL',
     'HOMEIMPROVEMENT', ' DEBTCONSOLIDATION ',   'DEBTCONSOLIDATION']
Length: 9, dtype: str

In [26]:
df['loan_intent'].unique()

<StringArray>
[           'personal',           'EDUCATION',             'MEDICAL',
             'VENTURE',         ' EDUCATION ',            'PERSONAL',
     'HOMEIMPROVEMENT', ' DEBTCONSOLIDATION ',   'DEBTCONSOLIDATION']
Length: 9, dtype: str

In [49]:
df['person_gender'].replace('MALE','male')

0        female
1        female
2        female
3        female
4          male
          ...
47245      male
47246      male
47247    female
47248      male
47249      male
Name: person_gender, Length: 47250, dtype: str

In [50]:
df['person_gender'].unique()

<StringArray>
['female', 'MALE', 'male']
Length: 3, dtype: str

In [51]:
df['person_gender'].replace('FEMALE','female')

0        female
1        female
2        female
3        female
4          MALE
          ...
47245      MALE
47246      male
47247    female
47248      MALE
47249      male
Name: person_gender, Length: 47250, dtype: str

In [56]:
df['person_gender'].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [55]:
df['person_gender']=df['person_gender'].replace('MALE','male')

In [ ]:
df['person_gender']=df['person_gender'].replace('MALE','male')

In [57]:
df['loan_intent']=df['loan_intent'].replace( ' EDUCATION ','EDUCATION')

In [58]:
df['loan_intent']=df['loan_intent'].replace('personal','PERSONAL')

In [59]:
df['loan_intent']=df['loan_intent'].replace(' DEBTCONSOLIDATION ','DEBTCONSOLIDATION')

In [60]:
df['loan_intent'].unique()

<StringArray>
[         'PERSONAL',         'EDUCATION',           'MEDICAL',
           'VENTURE',   'HOMEIMPROVEMENT', 'DEBTCONSOLIDATION']
Length: 6, dtype: str

In [61]:
df['person_education']=df['person_education'].replace(' High School ','High School')

In [66]:
df['person_education'].unique()

<StringArray>
['MASTER', 'High School', 'Bachelor', 'Associate', 'Doctorate']
Length: 5, dtype: str

In [63]:
df['person_education']=df['person_education'].replace('Master','Master')

In [65]:
df['person_education']=df['person_education'].replace(' Bachelor ','Bachelor')

In [37]:
df["loan_status"].sum()

np.int64(10487)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47250 entries, 0 to 47249
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      47250 non-null  int64
 1   person_age                      47250 non-null  float64
 2   person_gender                   47250 non-null  str
 3   person_education                47250 non-null  str
 4   person_income                   47250 non-null  str
 5   person_emp_exp                  47250 non-null  int64
 6   person_home_ownership           47250 non-null  str
 7   loan_amnt                       47250 non-null  str
 8   loan_intent                     47250 non-null  str
 9   loan_int_rate                   47250 non-null  float64
 10  loan_percent_income             47250 non-null  float64
 11  cb_person_cred_hist_length      47250 non-null  float64
 12  credit_score                    47250 non-null  int64
 13  previous_loan_defaults_on_file  47250 non-null  str
 14  loan_status                     47250 non-null  int64
dtypes: float64(4), int64(4), str(7)
memory usage: 5.4 MB

In [10]:
df.isnull().sum()

Unnamed: 0                        0
person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

## Part 1: Exploratory Data Analysis (EDA)
* What insights did you gain from your EDA? Are there missing values? Outliers? Is the target variable balanced or imbalanced? Use visualizations to support your findings.

In [ ]:
# Your EDA code here 
# Note: you are not required to answer in this single cell, create more cells if needed

## Part 2: Data Preprocessing
* Explain your strategy for handling categorical variables (e.g., One-Hot Encoding vs Label Encoding) and missing data.  
**Crucial:** Remember to split your data into training and testing sets BEFORE applying scaling to prevent data leakage.

In [ ]:
# Your preprocessing, train_test_split, and scaling code here
# Note: you are not required to answer in this single cell, create more cells if needed

## Part 3: Modeling
* Train your models.

In [ ]:
# Model 1 Training & Prediction
# Note: you are not required to answer in this single cell, create more cells if needed

In [ ]:
# Model 2 Training & Prediction
# Note: you are not required to answer in this single cell, create more cells if needed

## Part 4: Evaluation
* Output the classification reports and confusion matrices for all models.

In [ ]:
# Evaluation metrics
# Note: you are not required to answer in this single cell, create more cells if needed

## Part 5: Final Comparative Analysis
*(Double click this cell to edit)*

**Write your final conclusions here:**
Which model performed best according to your metrics, and why do you think that is?